/* Autor: Oscar Fuentes Alvarado
 * Fecha de creación: 01 de junio de 2022
 * Fecha de actualización: 09 de junio de 2022
 * Descripción: clase JPanel para controlar las operaciones CRUD
                aplicados a los objetos Prestamos, además enlazamos
                las listas provenientes de otros páneles para ocupar
                su información
 */
package view;

import controller.EncargadoController;
import controller.PrestamoController;
import controller.LibroController;
import controller.UsuarioController;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pojo.Usuario;
import pojo.Libro;
import pojo.Encargado;
import pojo.Prestamo;

/**
 *
 * @author oscar
 */
public class PanelPrestamo extends javax.swing.JPanel {

    private List<Libro> listaLibro;
    private List<Usuario> listaAlumno;
    private List<Encargado> listaEncargado;
    private List<Prestamo> listaPrestamo;

    private PrestamoController prestController;
    private DefaultTableModel modelo;
    private List<String> listaIsbn;

    private LibroController libroAux;
    private UsuarioController alumnoAux;
    private EncargadoController encargadoAux;

    private int id;

    /**
     * Creates new form Panel1
     */
    public PanelPrestamo(List<Libro> listLibro, List<Usuario> listAlumno,
            List<Encargado> listEncargado) {
        initComponents();

        prestController = new PrestamoController();
        listaLibro = listLibro;
        listaAlumno = listAlumno;
        listaEncargado = listEncargado;

        libroAux = new LibroController();
        alumnoAux = new UsuarioController();
        encargadoAux = new EncargadoController();

        listaPrestamo = new ArrayList<>();
        modelo = (DefaultTableModel) jTable1.getModel();
        listaIsbn = new ArrayList<>();

    }

    public void limpiar() {
        jText_FechaSol.setText("00/00/0000");
        jText_FechaEnt.setText("00/00/0000");
        jText_Matricula.setText("");
        jText_Encargado.setText("");
        jText_ArrayIsbn.setText("isbn");
    }

    public Prestamo leer() {
        Prestamo prestamoLeer = new Prestamo();
        prestamoLeer.setId(id);
        prestamoLeer.setFechaSol(jText_FechaSol.getText());
        prestamoLeer.setFechaEnt(jText_FechaEnt.getText());
        prestamoLeer.setMatricula(jText_Matricula.getText());
        prestamoLeer.setCodTrab(jText_Encargado.getText());
        if (jText_ArrayIsbn.getText().equals("")) {
        } else {
            String nuevo = jText_ArrayIsbn.getText();
            listaIsbn.add(nuevo);
        }
        prestamoLeer.setNombres(listaIsbn);
        return prestamoLeer;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jText_FechaSol = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jText_FechaEnt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jText_Matricula = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jText_Encargado = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jText_ArrayIsbn = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 51));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(39, 154, 180));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(98, 193, 222));
        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 95, -1));

        jButton2.setBackground(new java.awt.Color(98, 193, 222));
        jButton2.setText("Actualizar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 95, -1));

        jButton3.setBackground(new java.awt.Color(98, 193, 222));
        jButton3.setText("Eliminar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 95, -1));

        jButton5.setBackground(new java.awt.Color(98, 193, 222));
        jButton5.setText("Borrar");
        jButton5.setPreferredSize(new java.awt.Dimension(78, 24));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        add(jPanel1, java.awt.BorderLayout.LINE_END);

        jPanel2.setBackground(new java.awt.Color(100, 176, 176));

        jLabel1.setText("Solicitud");

        jText_FechaSol.setBackground(new java.awt.Color(39, 154, 180));
        jText_FechaSol.setText("00/00/0000");
        jText_FechaSol.setMaximumSize(new java.awt.Dimension(150, 20));

        jLabel2.setText("Entrega");

        jText_FechaEnt.setBackground(new java.awt.Color(39, 154, 180));
        jText_FechaEnt.setText("00/00/0000");
        jText_FechaEnt.setMaximumSize(new java.awt.Dimension(200, 20));

        jLabel3.setText("Matrícula");

        jText_Matricula.setBackground(new java.awt.Color(39, 154, 180));
        jText_Matricula.setMaximumSize(new java.awt.Dimension(90, 20));
        jText_Matricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_MatriculaActionPerformed(evt);
            }
        });

        jLabel4.setText("Encargado");

        jText_Encargado.setBackground(new java.awt.Color(39, 154, 180));
        jText_Encargado.setMaximumSize(new java.awt.Dimension(150, 20));

        jLabel5.setText("Libros");

        jText_ArrayIsbn.setBackground(new java.awt.Color(39, 154, 180));
        jText_ArrayIsbn.setText("isbn");

        jTable1.setBackground(new java.awt.Color(66, 248, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Fecha Solicitud", "Fecha entrega", "Matrícula", "Encargado", "Libros"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setSelectionBackground(new java.awt.Color(153, 153, 255));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(35);
        }

        jButton6.setBackground(new java.awt.Color(0, 255, 222));
        jButton6.setText("Añadir");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jText_FechaSol, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                            .addComponent(jText_Encargado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jText_FechaEnt, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                            .addComponent(jText_ArrayIsbn))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(16, 16, 16)
                                .addComponent(jText_Matricula, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton6))
                        .addGap(4, 4, 4)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jText_FechaSol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jText_FechaEnt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addComponent(jText_Matricula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jText_Encargado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jText_ArrayIsbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6))
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jText_MatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_MatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_MatriculaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        Prestamo prestamo = new Prestamo();

        Usuario alumno = alumnoAux.getUsuario(listaAlumno,
                jText_Matricula.getText());
        Libro libro = libroAux.getLibro(listaLibro, jText_ArrayIsbn.getText());
        Encargado encargado = encargadoAux.getEncargado(listaEncargado,
                jText_Encargado.getText());

        if (jText_FechaSol.getText().equals("")
                || jText_FechaEnt.getText().equals("")
                || jText_Matricula.getText().equals("")
                || jText_Encargado.getText().equals("")
                || jText_ArrayIsbn.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Rellena todos los campos");
        } else if (alumno == null) {
            JOptionPane.showMessageDialog(null, "El alumno no existe\n"
                    + "regístralo antes");
        } else if (libro == null) {
            JOptionPane.showMessageDialog(null, "El libro no existe");
        } else if (encargado == null) {
            JOptionPane.showMessageDialog(null, "El encargado no existe\n "
                    + "regístralo");
        } else {
            prestamo = leer();
            listaPrestamo = prestController.crearPrestamo(listaPrestamo,
                    prestamo);
            limpiar();
            jText_FechaSol.setEditable(true);
            List<String> vacio = new ArrayList<>();
            listaIsbn = vacio;
        }

        prestController.mostrarPrestamo(listaPrestamo, listaLibro,
                listaEncargado, listaAlumno, modelo);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (jText_FechaSol.getText().equals("")
                || jText_FechaEnt.getText().equals("")
                || jText_Matricula.getText().equals("")
                || jText_Encargado.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Rellena todos los campos");
        } else {
            Prestamo leerD = leer();
            Prestamo prestamo23 = prestController.getPrestamo(listaPrestamo,
                    leerD);
            //JOptionPane.showMessageDialog(null, leerD.getCodTrab());
            //JOptionPane.showMessageDialog(null, prestamo23.getCodTrab());
            if (prestamo23 != null) {
                listaPrestamo = prestController.eliminarPrestamo(listaPrestamo,
                        leerD);

                limpiar();
            } else {
                JOptionPane.showMessageDialog(null, "No hay registro "
                        + "del prestamo");

            }
        }
        prestController.mostrarPrestamo(listaPrestamo, listaLibro,
                listaEncargado, listaAlumno, modelo);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Prestamo prestamo1 = new Prestamo();
        if (jText_FechaSol.getText().equals("")
                || jText_FechaEnt.getText().equals("")
                || jText_Matricula.getText().equals("")
                || jText_Encargado.getText().equals("")
                || jText_ArrayIsbn.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Rellena todos los campos");
        } else {
            prestamo1 = leer();
            listaPrestamo = prestController.actualizarPrestamo(listaPrestamo,
                    id, prestamo1);
            prestController.mostrarPrestamo(listaPrestamo, listaLibro,
                    listaEncargado, listaAlumno, modelo);

            limpiar();
            jText_FechaSol.setEditable(true);
            List<String> vacio = new ArrayList<>();
            listaIsbn = vacio;

        }

        jText_FechaSol.setEditable(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        id = Integer.parseInt(jTable1.getValueAt(jTable1.getSelectedRow(),
                0).toString());
        jText_FechaSol.setText(jTable1.getValueAt(jTable1.getSelectedRow(),
                1).toString());
        jText_FechaEnt.setText(jTable1.getValueAt(jTable1.getSelectedRow(),
                2).toString());
        jText_Matricula.setText(jTable1.getValueAt(jTable1.getSelectedRow(),
                3).toString());
        jText_Encargado.setText(jTable1.getValueAt(jTable1.getSelectedRow(),
                4).toString());
        jText_ArrayIsbn.setText(jTable1.getValueAt(jTable1.getSelectedRow(),
                5).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        limpiar();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        String isbn1 = jText_ArrayIsbn.getText();

        Libro libroBuscar = libroAux.getLibro(listaLibro, isbn1);
        if (libroBuscar != null) {
            listaIsbn.add(isbn1);
        } else {
            JOptionPane.showMessageDialog(null, "no hay registro del libro");
        }

    }//GEN-LAST:event_jButton6ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jText_ArrayIsbn;
    private javax.swing.JTextField jText_Encargado;
    private javax.swing.JTextField jText_FechaEnt;
    private javax.swing.JTextField jText_FechaSol;
    private javax.swing.JTextField jText_Matricula;
    // End of variables declaration//GEN-END:variables
}
