/* Autor: Oscar Fuentes Alvarado
 * Fecha de creación: 26 de mayo de 2022
 * Fecha de actualización: 09 de junio de 2022
 * Descripción: Clase JFrame para controlar el programa, aquí enlazamos
                las clases que muestran una interfaz para cada objeto
 */
package view;

import controller.EncargadoController;
import controller.LibroController;
import controller.UsuarioController;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import pojo.Usuario;
import pojo.Libro;
import pojo.Encargado;

/**
 *
 * @author oscar
 */
public class VentanaPrincipal extends javax.swing.JFrame implements ActionListener {

    private List<Libro> listaLibro = new ArrayList<>();
    private List<Usuario> listaAlumno = new ArrayList<>();
    private List<Encargado> listaEncargado = new ArrayList<>();

    PanelLibro panelLib;
    PanelAlumno panelAlum;
    PanelEncargado panelEnc;
    PanelPrestamo panelPrest;

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);

        insertar();
        panelLib = new PanelLibro(listaLibro);
        panelAlum = new PanelAlumno(listaAlumno);
        panelEnc = new PanelEncargado(listaEncargado);
        panelPrest = new PanelPrestamo(listaLibro, listaAlumno, listaEncargado);

        contenedor.add(panelLib);

        panelLib.setVisible(true);
        panelAlum.setVisible(false);
        panelEnc.setVisible(false);
        panelPrest.setVisible(false);
        deshabilitarBotones();

        boton_Lib.addActionListener(this);
        boton_Alum.addActionListener(this);
        boton_Enc.addActionListener(this);
        boton_Prest.addActionListener(this);

    }

    private void deshabilitarBotones() {
        if (panelLib.isVisible()) {
            boton_Lib.setEnabled(false);
            boton_Alum.setEnabled(true);
            boton_Enc.setEnabled(true);
            boton_Prest.setEnabled(true);
        } else if (panelAlum.isVisible()) {
            boton_Lib.setEnabled(true);
            boton_Alum.setEnabled(false);
            boton_Enc.setEnabled(true);
            boton_Prest.setEnabled(true);
        } else if (panelEnc.isVisible()) {
            boton_Lib.setEnabled(true);
            boton_Alum.setEnabled(true);
            boton_Enc.setEnabled(false);
            boton_Prest.setEnabled(true);
        } else if (panelPrest.isVisible()) {
            boton_Lib.setEnabled(true);
            boton_Alum.setEnabled(true);
            boton_Enc.setEnabled(true);
            boton_Prest.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedor = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        boton_Enc = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        boton_Prest = new javax.swing.JButton();
        boton_Alum = new javax.swing.JButton();
        boton_Lib = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(675, 400));

        contenedor.setPreferredSize(new java.awt.Dimension(800, 400));
        contenedor.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setBackground(new java.awt.Color(153, 153, 255));
        jLabel1.setFont(new java.awt.Font("Bitstream Charter", 1, 18)); // NOI18N
        jLabel1.setText("Sistema de adiminstración de Biblioteca");
        jPanel2.add(jLabel1);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/biblioteca32x32.png"))); // NOI18N
        jLabel6.setMaximumSize(new java.awt.Dimension(60, 60));
        jLabel6.setMinimumSize(new java.awt.Dimension(60, 60));
        jPanel2.add(jLabel6);

        contenedor.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel4.setBackground(new java.awt.Color(0, 153, 153));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/libros32x32.png"))); // NOI18N
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/alumno32x32.png"))); // NOI18N
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/encargado32x32.png"))); // NOI18N
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        boton_Enc.setBackground(new java.awt.Color(112, 122, 255));
        boton_Enc.setText("Encargado");
        jPanel4.add(boton_Enc, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 105, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/prestamo32x32.png"))); // NOI18N
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        boton_Prest.setBackground(new java.awt.Color(112, 122, 255));
        boton_Prest.setText("Préstamos");
        jPanel4.add(boton_Prest, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 105, -1));

        boton_Alum.setBackground(new java.awt.Color(112, 122, 255));
        boton_Alum.setText("Alumnos");
        jPanel4.add(boton_Alum, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 105, -1));

        boton_Lib.setBackground(new java.awt.Color(112, 122, 255));
        boton_Lib.setText("Libros");
        boton_Lib.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_LibActionPerformed(evt);
            }
        });
        jPanel4.add(boton_Lib, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 105, -1));

        jButton1.setBackground(new java.awt.Color(85, 125, 222));
        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, -1, -1));

        contenedor.add(jPanel4, java.awt.BorderLayout.LINE_START);

        getContentPane().add(contenedor, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void boton_LibActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_LibActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton_LibActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_Alum;
    private javax.swing.JButton boton_Enc;
    private javax.swing.JButton boton_Lib;
    private javax.swing.JButton boton_Prest;
    private javax.swing.JPanel contenedor;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent ae) {
        Object evt = ae.getSource();
        if (evt.equals(boton_Lib)) {
            panelLib.setVisible(true);
            panelAlum.setVisible(false);
            panelEnc.setVisible(false);
            panelPrest.setVisible(false);
            contenedor.add(panelLib);
            contenedor.validate();
            deshabilitarBotones();
        } else if (evt.equals(boton_Alum)) {
            panelLib.setVisible(false);
            panelAlum.setVisible(true);
            panelEnc.setVisible(false);
            panelPrest.setVisible(false);
            contenedor.add(panelAlum);
            contenedor.validate();
            deshabilitarBotones();
        } else if (evt.equals(boton_Enc)) {
            panelLib.setVisible(false);
            panelAlum.setVisible(false);
            panelEnc.setVisible(true);
            panelPrest.setVisible(false);
            contenedor.add(panelEnc);
            contenedor.validate();
            deshabilitarBotones();
        } else if (evt.equals(boton_Prest)) {
            panelLib.setVisible(false);
            panelAlum.setVisible(false);
            panelEnc.setVisible(false);
            panelPrest.setVisible(true);
            contenedor.add(panelPrest);
            contenedor.validate();
            deshabilitarBotones();
        }
    }

    public void insertar() {
        Libro libro1 = new Libro();
        Libro libro2 = new Libro();
        Libro libro3 = new Libro();
        LibroController uno = new LibroController();

        Usuario user1 = new Usuario();
        Usuario user2 = new Usuario();
        UsuarioController dos = new UsuarioController();

        Encargado enc1 = new Encargado();
        Encargado enc2 = new Encargado();
        EncargadoController tres = new EncargadoController();

        libro1.setIsbn("978-84-939750");
        libro1.setTitulo("El corazón de la piedra");
        libro1.setClasificacion("Novela");
        libro1.setAutor("José María G.");
        libro1.setCantidad((short) 2);

        libro2.setIsbn("84-932914-8-X");
        libro2.setTitulo("Salmos de vísperas");
        libro2.setClasificacion("Drama");
        libro2.setAutor("Esteban Hernández");
        libro2.setCantidad((short) 1);

        libro3.setIsbn("84-206-9070-8");
        libro3.setTitulo("El canto gregoriano");
        libro3.setClasificacion("Novela");
        libro3.setAutor("Juan Carlos A.");
        libro3.setCantidad((short) 3);
        uno.crearLibro(listaLibro, libro1);
        uno.crearLibro(listaLibro, libro2);
        uno.crearLibro(listaLibro, libro3);

        user1.setCarrera("Medicina");
        user1.setMatricula("203097654");
        user1.setNombre("Ana Díaz");
        user1.setSemestre("Quinto");

        user2.setCarrera("Informática");
        user2.setMatricula("203887649");
        user2.setNombre("Laura Sánchez");
        user2.setSemestre("Cuarto");
        dos.crearUsuario(listaAlumno, user1);
        dos.crearUsuario(listaAlumno, user2);

        enc1.setCodTrab("2020876");
        enc1.setNombre("María Agudo");
        enc1.setTelefono("9514370922");

        enc2.setCodTrab("2020654");
        enc2.setNombre("Lorenzo Arty");
        enc2.setTelefono("9516178402");
        tres.crearEncargado(listaEncargado, enc1);
        tres.crearEncargado(listaEncargado, enc2);
    }
}
